name: Build and deploy to Azure Container Registry

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: respotify.azurecr.io
        username: ${{ secrets.ACR_REGISTRY_USERNAME }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD }}
    - run: |
        docker build . -t respotify.azurecr.io/frontend
        docker push respotify.azurecr.io/frontend
