name: Update Deployment
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_CLUSTER_NAME }} --overwrite-existing

      - name: Rollout Restart Frontend on AKS
        run: kubectl rollout restart deployment/frontend
        continue-on-error: true #If aks cluster is not available, the pipeline should not fail
      
