on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_RESOURCE_GROUP }} --overwrite-existing

      - name: Rollout Restart Frontend on AKS
        run: kubectl rollout restart deployment/frontend
        continue-on-error: true #If aks cluster is not available, the pipeline should not fail
      
